This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./elteikthesis_en.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file elteikthesis_en.acn....done (256 entries accepted, 0 rejected).
Sorting entries.....done (2248 comparisons).
Generating output file elteikthesis_en.acr....done (139 lines written, 0 warnings).
Output written in elteikthesis_en.acr.
Transcript written in elteikthesis_en.alg.
